/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafemenu;

/**
 *
 * @author Administrator
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfieldUcret = new javax.swing.JTextField();
        cbAmericano = new javax.swing.JCheckBox();
        labelMenu = new javax.swing.JLabel();
        cbLatte = new javax.swing.JCheckBox();
        cbMocha = new javax.swing.JCheckBox();
        cbCappuccino = new javax.swing.JCheckBox();
        cbTurkKahvesi = new javax.swing.JCheckBox();
        cbFilterCoffe = new javax.swing.JCheckBox();
        buttonHesapla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tfieldUcret.setBackground(new java.awt.Color(204, 204, 204));
        tfieldUcret.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        tfieldUcret.setForeground(new java.awt.Color(0, 0, 0));
        tfieldUcret.setText("ÜCRET : 0 TL");
        tfieldUcret.setBorder(null);
        tfieldUcret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldUcretActionPerformed(evt);
            }
        });

        cbAmericano.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbAmericano.setForeground(new java.awt.Color(0, 102, 102));
        cbAmericano.setText("Americano - 47₺");
        cbAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAmericanoActionPerformed(evt);
            }
        });

        labelMenu.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelMenu.setForeground(new java.awt.Color(0, 0, 0));
        labelMenu.setText("MENU");

        cbLatte.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbLatte.setForeground(new java.awt.Color(0, 102, 102));
        cbLatte.setText("Latte - 54₺");
        cbLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLatteActionPerformed(evt);
            }
        });

        cbMocha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbMocha.setForeground(new java.awt.Color(0, 102, 102));
        cbMocha.setText("Mocha - 72₺");
        cbMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMochaActionPerformed(evt);
            }
        });

        cbCappuccino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbCappuccino.setForeground(new java.awt.Color(0, 102, 102));
        cbCappuccino.setText("Cappuccino - 54₺");
        cbCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCappuccinoActionPerformed(evt);
            }
        });

        cbTurkKahvesi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTurkKahvesi.setForeground(new java.awt.Color(0, 102, 102));
        cbTurkKahvesi.setText("Türk Kahvesi - 40₺");
        cbTurkKahvesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurkKahvesiActionPerformed(evt);
            }
        });

        cbFilterCoffe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbFilterCoffe.setForeground(new java.awt.Color(0, 102, 102));
        cbFilterCoffe.setText("Filter Coffe - 44₺");
        cbFilterCoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilterCoffeActionPerformed(evt);
            }
        });

        buttonHesapla.setBackground(new java.awt.Color(204, 204, 204));
        buttonHesapla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonHesapla.setForeground(new java.awt.Color(0, 0, 153));
        buttonHesapla.setText("HESAPLA");
        buttonHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbAmericano, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(labelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(cbCappuccino))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonHesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMocha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfieldUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbTurkKahvesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbFilterCoffe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTurkKahvesi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLatte, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFilterCoffe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMocha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonHesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tfieldUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAmericanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAmericanoActionPerformed

    private void cbLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLatteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLatteActionPerformed

    private void cbMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMochaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMochaActionPerformed

    private void cbCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCappuccinoActionPerformed

    private void cbTurkKahvesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurkKahvesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurkKahvesiActionPerformed

    private void cbFilterCoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilterCoffeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilterCoffeActionPerformed

    private void buttonHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHesaplaActionPerformed
        // TODO add your handling code here:
        int ucret = 0;
        
        if(cbAmericano.isSelected()) {
            ucret = ucret + 47;
        }
        
        if(cbLatte.isSelected()) {
            ucret = ucret + 54;
        }
        
        if(cbMocha.isSelected()) {
            ucret = ucret + 72;
        }
        
        if(cbCappuccino.isSelected()) {
            ucret = ucret + 54;
        }
        
        if(cbTurkKahvesi.isSelected()) {
            ucret = ucret + 40;
        }
        
        if(cbFilterCoffe.isSelected()) {
            ucret = ucret + 44;
        }
        
        tfieldUcret.setText("ÜCRET: " + ucret + "₺");
    }//GEN-LAST:event_buttonHesaplaActionPerformed

    private void tfieldUcretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldUcretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldUcretActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHesapla;
    private javax.swing.JCheckBox cbAmericano;
    private javax.swing.JCheckBox cbCappuccino;
    private javax.swing.JCheckBox cbFilterCoffe;
    private javax.swing.JCheckBox cbLatte;
    private javax.swing.JCheckBox cbMocha;
    private javax.swing.JCheckBox cbTurkKahvesi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JTextField tfieldUcret;
    // End of variables declaration//GEN-END:variables
}
